/* Copyright 1996 Acorn Computers Ltd
 * Copyright 1998 Acorn Computers Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is a reimplementation in C of RISC OS Open's International Keyboard
 * module (Sources/Internat/IntKey: Source.IntKeyBody, Source.KeyStruct, c.keygen).
 */

/* keylayout.h: a keyboard layout as keygen (Internat/IntKey) makes it,
 * and the tables that every layout shares. The data is generated by
 * tools/keylayout.py from the RISC OS sources into the build tree. */
#ifndef ROSGD_KEYLAYOUT_H
#define ROSGD_KEYLAYOUT_H

#include <stdint.h>

struct ros_keylayout {
    uint32_t country;               /* the country it is for (Country_UK is 1, and so on) */
    uint32_t wide;                  /* 16-bit key numbers (not carried so far) */
    const uint8_t *keytran;         /* 4 bytes a key: plain, Shift, Ctrl, Ctrl-Shift. &FF means a special key */
    const uint16_t *keytran_w;
    uint32_t keytran_size;          /* keys */
    const uint16_t *special;        /* special keys. A special number is the index plus 1 */
    uint32_t nspecial;
    uint32_t pad_first, ucs_first;  /* the special numbers of the first keypad key
                                       and the first Unicode key */
    const uint32_t *ucs0, *ucs1;    /* 9 words for each Unicode key, from ucs_first:
                                       plain, Shift, Ctrl, Ctrl-Shift, Alt, Alt-Shift,
                                       Alt-Ctrl, Alt-Ctrl-Shift, and the Caps Lock word.
                                       ucs0 is the first layer and ucs1 the second
                                       layer (Kana). */
    const uint8_t *pad_num, *pad_cur;   /* the layout's own keypad, or 0 */
};

extern const struct ros_keylayout ros_keylayout_uk;

extern const uint32_t ros_intkey_inkeytran[128];    /* InkeyTranPC */
extern const uint8_t ros_intkey_shifting[];         /* ShiftingKeyList */
extern const uint8_t ros_intkey_pad_num[17], ros_intkey_pad_cur[17];
extern const uint32_t *const ros_intkey_accents[];  /* AccentTable: pairs, sorted */

#endif
