#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alban Read
"""patch-basicasm.py: wires the cross assemblers (asmlib/) into the
generated ROM C.

gen/rom_basicvfp.c is regenerated by `rosasm --emit c`. This script applies
the hooks after every regeneration. It is idempotent, because each step
checks whether it has already been applied. A site that it cannot find is an
error. That means the generator's output has changed and the hooks need a
look.

BASIC's '[' runs the ROM's ARM assembler (s.Assembler) for every CPU. That
covers statements, labels, OPT and the listing, P%/O%/L%, the directives, FN
macros and errors. *BasicAsmCPU X64 or A64 changes only what an instruction
becomes (asmlib/basicasm.c). The hooks are:

  CASM     This runs before the mnemonic is looked up. The site is
           CMP R10,#&7F; BHS CASMTOK, and it is before the VFP assembler's V
           as well. basicasm_statement() encodes an x86-64 or AArch64
           instruction. The ARM assembler then goes on at CASMICHK for an
           A64 word (in R1), or at CASMXCHK for x86-64 bytes (in STRACC, with
           R2 as their end). It may go on at one of its error entries
           instead. A directive is left to the ARM assembler.
  CASMX    This is where the ARM assembler lists an instruction's word.
           basicasm_list_bytes() lists x86-64 bytes instead, and then CASMX1
           writes the source.
  ASS      This is '['. basicasm_block(ARGP) begins a block. An ARM program
           recognised before is forgotten if another program runs.
  CASM1A   This is '.name'. basicasm_label() notes the label's variable and
           P%. x86-64 takes these as settled for the rest of the block.
  CASMKET  This is ']', whatever the CPU. basicasm_ket() ends the block. It
           registers the block's code for CALL and USR, or it forgets code
           registered there if that code is for another CPU.
  TSTVB1   This is a name with no variable, read as P% (with the errors bit
           of OPT clear). basicasm_unknown counts it as a forward reference.
  MSG      This is BASIC's error handler, about to go on at STMT. An error
           in an operand comes back to the statement it abandons. That
           statement goes on at STMT itself, and the C frames between are
           gone (see basicasm.c).

There is also one hook that does not belong to the assembler:

  FNGOACACHE  This is where an FN or PROC call asks BASIC's stack for room.
           The test is FSA + 1K below SP, and otherwise ERDEEPPROC. The
           thread's native stack is asked as well (ros_stack_room,
           ROS_STACK_BASIC; see task.h). A recursion that is too deep for it
           then gives BASIC's own "No room for function/procedure call"
           error, and not a SIGSEGV (#64).

EXPR is exported. basicasm.c evaluates operands with it, as ASMEXPR does.
BASIC105 is not patched, so the assembler in *BASIC is ARM only.
"""
import re
import sys
import os

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    'gen', 'rom_basicvfp.c')

MARK = 'asmlib/basicasm.c'      # in every hook, so that a patched file is recognised

EXPORTS = ['EXPR']

ERRORS = [('BASICASM_ERASS1', 'ERASS1'), ('BASICASM_ERSYNT', 'ERSYNT'),
          ('BASICASM_ERASS3', 'ERASS3'), ('BASICASM_ERASS2', 'ERASS2'),
          ('BASICASM_ERASS2A', 'ERASS2A'), ('BASICASM_ERASS2S', 'ERASS2S'),
          ('BASICASM_ERTYPEINT', 'ERTYPEINT'), ('BASICASM_ERDEEPNEST', 'ERDEEPNEST'),
          ('BASICASM_FACERR', 'FACERR')]

CASM_SITE = '''                                                /* CMP R10,#&7F */
    if (r10 >= 0x7Fu) {                         /* BHS CASMTOK */
'''

CASMX_SITE = '''    r10 = r1;                                   /* MOV R10,R1 */
    ros_subs(s, r2, 5);                         /* CMP R2,#5 */
'''

KET_SITE = '''        ros_st8(r8 - 26, 0xFFFFFFFFu);          /* STRB R0,[ARGP,#BYTESM] */
        r0 = r10;                               /* MOV R0, R10 */
'''

MSG_SITE = '''    { R[13] = r13; ROS_TAIL_CALL(basicvfp_STMT) } /* B STMT ; continue from LINE */
'''

FNROOM_SITE = '''    if (r4 >= r13) {                            /* BCS ERDEEPPROC */
'''

TSTVB1_SITE = '''ROS_TAIL_CALL(basicvfp_FACERR) } /* BNE FACERR */
    r0 = ros_ld32(r8 - 192);                    /* LDR R0,[ARGP,#ASSPC] */
'''

ASS_SITE = '''ASS: ;
'''

# CASM1A, in CASM: R4 is the label's variable (LV's IACC) and R0 is P%. STOREA is about to be called.
LABEL_SITE = '''        r9 = 4;                                 /* MOV TYPE,#4 */
        R[0] = r0; R[4] = r4; R[5] = r5; R[9] = r9; /* BL STOREA */
'''


def fail(why):
    sys.exit('patch-basicasm.py: %s -- generator output changed?' % why)


def function(src, name):
    """[start, end) of basicvfp_NAME's definition"""
    m = re.search(r'\nstatic void basicvfp_%s\(struct ros_cpu \*s\)\n\{\n' % name, src)
    if not m:
        fail('no region ' + name)
    end = src.find('\n}\n', m.end())
    return m.start(), end


def registers(src, name):
    """the rN locals basicvfp_NAME declares, to store back into R[]"""
    a, _ = function(src, name)
    decl = src[src.index('{\n', a) + 2:]
    decl = decl[:decl.index(';\n')]
    if not decl.lstrip().startswith('uint32_t'):
        fail('%s declares no registers first' % name)
    return sorted({int(r) for r in re.findall(r'\br(\d+)\b', decl)})


def stores(regs, indent):
    return indent + ' '.join('R[%d] = r%d;' % (r, r) for r in regs) + '\n'


def insert_in(src, name, site, text, after=False):
    a, b = function(src, name)
    body = src[a:b]
    if body.count(site) != 1:
        fail('%d sites in %s' % (body.count(site), name))
    body = body.replace(site, site + text if after else text + site)
    return src[:a] + body + src[b:]


def main():
    src = open(SRC).read()
    if MARK in src:
        print('patch-basicasm: already patched')
        return

    anchor = '#include "rom_basicvfp.h"'
    if anchor not in src:
        anchor = '#include "rosgd/error.h"'
    if anchor not in src:
        fail('no include anchor')
    src = src.replace(anchor, anchor + '\n#include "basicasm.h"          /* the cross assemblers: %s */'
                      % MARK, 1)

    # CASM: an x86-64 or AArch64 instruction
    regs = registers(src, 'CASM')
    cases = ''.join('        case %s: ROS_TAIL_CALL(basicvfp_%s)\n' % e for e in ERRORS)
    hook = ('    if (basicasm_cpu_mode()) {                  /* x86-64, AArch64: %s */\n' % MARK +
            stores(regs, '        ') +
            '        switch (basicasm_statement(s)) {\n'
            '        case BASICASM_WORD: ROS_TAIL_CALL(basicvfp_CASMICHK)\n'
            '        case BASICASM_BYTES: ROS_TAIL_CALL(basicvfp_CASMXCHK)\n' + cases +
            # EINVOP is not a routine. It is the fall-through in VFPException.
            # It is FIX's invalid operation, as when a real is too big, and the
            # ARM assembler's code leaves it that way.
            '        case BASICASM_EINVOP:\n'
            '            s->fp->fpscr = (s->fp->fpscr & ~(FPSCR_DZC | FPSCR_OFC)) | FPSCR_IOC;\n'
            '            ROS_TAIL_CALL(basicvfp_VFPException)\n' +
            '        case BASICASM_STMT: ROS_TAIL_CALL(basicvfp_STMT)\n' +
            '        default: break;                         /* a directive: the ARM assembler\'s */\n'
            '        }\n'
            '    }\n')
    src = insert_in(src, 'CASM', CASM_SITE, hook)

    # CASMX: x86-64's bytes in the listing
    regs = registers(src, 'CASMX')
    hook = ('    if (basicasm_list_bytes(s)) {               /* x86-64\'s bytes: %s */\n' % MARK +
            stores(regs, '        ') +
            '        ROS_TAIL_CALL(basicvfp_CASMX1)\n'
            '    }\n')
    src = insert_in(src, 'CASMX', CASMX_SITE, hook)

    # CASMKET, inlined in CASM: ']'. Where P% started is the word that the
    # LDMFD has just popped. This applies to every CPU, and ARM's code
    # forgets another CPU's.
    hook = ('        basicasm_ket(s, ros_ld32(r13 - 8), ros_ld32(r8 - 192)); /* the run path: %s */\n'
            % MARK)
    src = insert_in(src, 'CASM', KET_SITE, hook)

    # CASM1A, inlined in CASM: a label has been made
    hook = ('        basicasm_label(r4, r0);                 /* a label: %s */\n' % MARK)
    src = insert_in(src, 'CASM', LABEL_SITE, hook, after=False)

    # ASS: '[' begins a block
    if src.count(ASS_SITE) != 1:
        fail('%d ASS sites' % src.count(ASS_SITE))
    src = src.replace(ASS_SITE, ASS_SITE +
                      '    basicasm_block(r8);                         /* a block: %s */\n' % MARK)

    # MSG, going on at the error's handler: go back to the statement it leaves
    if src.count(MSG_SITE) != 1:
        fail('%d MSG sites' % src.count(MSG_SITE))
    src = src.replace(MSG_SITE, '    R[13] = r13;                                /* the statement it leaves: %s */\n'
                      '    basicasm_error_goes_on(s);\n' % MARK + MSG_SITE)

    # TSTVB1: a name read as P%
    if src.count(TSTVB1_SITE) != 1:
        fail('%d TSTVB1 sites' % src.count(TSTVB1_SITE))
    src = src.replace(TSTVB1_SITE, TSTVB1_SITE +
                      '    basicasm_unknown++;                         /* a forward reference: %s */\n'
                      % MARK)

    # FNGOACACHE: test the native stack's room as well as BASIC's
    a, b = function(src, 'FNGOACACHE')
    body = src[a:b]
    if body.count(FNROOM_SITE) != 1:
        fail('%d FNGOACACHE sites' % body.count(FNROOM_SITE))
    body = body.replace(FNROOM_SITE,
                        '    if (r4 >= r13 || !ros_stack_room(ROS_STACK_BASIC)) { /* BCS ERDEEPPROC; '
                        'the native stack too, task.h: %s */\n' % MARK)
    src = src[:a] + body + src[b:]
    src = src.replace(anchor, anchor + '\n#include "rosgd/task.h"             /* ros_stack_room: %s */'
                      % MARK, 1)

    for name in EXPORTS:
        decl = 'static void basicvfp_%s(struct ros_cpu *s);' % name
        defn = 'static void basicvfp_%s(struct ros_cpu *s)\n{' % name
        if decl not in src or defn not in src:
            fail('no %s to export' % name)
        src = src.replace(decl, decl[len('static '):]).replace(defn, defn[len('static '):])

    open(SRC, 'w').write(src)
    print('patch-basicasm: ASS, CASM, CASM1A, CASMX, CASMKET, TSTVB1, MSG and FNGOACACHE hooked; %s exported; wrote %s'
          % (', '.join(EXPORTS), SRC))


if __name__ == '__main__':
    main()
