//! The C back end (design/compiler.md, "The C back end"). It writes the IR
//! out as C99.
//!
//! It writes one file for each program. Each unit is a C function and each
//! block is a label. Temporaries are the function's locals. BASIC variables
//! are file-scope statics, and each has a flag that says whether it exists
//! yet (§4.2.3). Runtime operations are calls into runtime/rb_rt.h and
//! runtime/rb_gen.h. Strings and FN values are passed to them by address.

use std::fmt::Write;

use crate::ir::*;

pub fn emit(p: &Program, source: &str) -> String {
    let mut o = String::new();
    let _ = writeln!(o, "/* Generated by rosbas from {source}.  Do not edit. */");
    o.push_str("#include \"rb_gen.h\"\n\n");
    // Variables
    for (i, v) in p.vars.iter().enumerate() {
        let name = String::from_utf8_lossy(&v.name);
        match v.kind {
            VarKind::AtPct => continue,
            VarKind::Int => {
                let _ = write!(o, "static int32_t V{i};");
            }
            VarKind::Real => {
                let _ = write!(o, "static double V{i};");
            }
            VarKind::Str => {
                let _ = write!(o, "static rb_str V{i};");
            }
        }
        if !v.resident {
            let _ = write!(o, " static int D{i};");
        }
        let _ = writeln!(o, " /* {} */", name.replace("*/", "* /"));
    }
    for (i, a) in p.arrays.iter().enumerate() {
        let _ = writeln!(o, "static rb_array AS{i}; static rb_array *A{i} = &AS{i}; /* {}( */", String::from_utf8_lossy(&a.name).replace("*/", "* /"));
    }
    // Literals
    for (i, s) in p.strs.iter().enumerate() {
        let _ = writeln!(o, "static const uint8_t S{i}[] = {{{}}};", bytes(s));
    }
    let _ = writeln!(o, "static const uint8_t PROGRAM[] = {{{}}};", bytes(&p.tokenised));
    for (i, a) in p.asm.iter().enumerate() {
        let _ = writeln!(o, "static const uint8_t ASM{i}[] = {{{}}};", bytes(a));
    }
    for (i, r) in p.reals.iter().enumerate() {
        let _ = writeln!(o, "static rb_litcache R{i} = {{.text = \"{}\", .len = {}}};", String::from_utf8_lossy(r), r.len());
    }
    o.push('\n');
    for (k, u) in p.units.iter().enumerate() {
        let _ = writeln!(o, "{};", signature(k, u));
    }
    o.push('\n');
    for (k, u) in p.units.iter().enumerate() {
        unit(&mut o, p, k, u);
    }
    let mut set = String::new();
    if p.tables {
        tables(&mut o, p);
        set.push_str("    rb_prog = &PROG;\n");
    }
    // CLEAR, RUN and LOMEM= forget every variable except the resident
    // integers, and every array (§4.9.1)
    if p.clears {
        o.push_str("static void CLEARV(void)\n{\n");
        for (i, v) in p.vars.iter().enumerate() {
            if v.resident || v.kind == VarKind::AtPct {
                continue;
            }
            let z = if v.kind == VarKind::Str { format!("V{i}.len = 0") } else { format!("V{i} = 0") };
            let _ = writeln!(o, "    {z}; D{i} = 0;");
        }
        for i in 0..p.arrays.len() {
            let _ = writeln!(o, "    rb_arr_forget(&AS{i}); A{i} = &AS{i};");
        }
        o.push_str("}\n");
        set.push_str("    rb_clear_vars = CLEARV;\n");
    }
    // The suffix of an error in each library's code (§9.2.8)
    if !p.libs.is_empty() {
        o.push_str("static const char *const LIBNAMES[] = {0");
        for l in &p.libs {
            match l {
                Some(t) => {
                    let _ = write!(o, ", \"{}\"", c_string(t));
                }
                None => o.push_str(", 0"),
            }
        }
        o.push_str("};\n");
        let _ = writeln!(set, "    rb_libnames = LIBNAMES;");
    }
    // RUN starts the main program again (§4.9.3)
    let entry = if p.runs {
        o.push_str("static void START(void)\n{\n    (void)setjmp(rb_run_jb);\n    U0();\n}\n");
        "START"
    } else {
        "U0"
    };
    let _ = writeln!(o, "int main(void)\n{{\n{set}    return rb_main({entry}, {}u, PROGRAM, sizeof PROGRAM);\n}}", p.quirks);
    o
}

fn bytes(s: &[u8]) -> String {
    if s.is_empty() {
        return "0".to_string();
    }
    s.iter().map(|b| b.to_string()).collect::<Vec<_>>().join(",")
}

fn ctype(t: Ty) -> &'static str {
    match t {
        Ty::Num => "rb_num",
        Ty::Str => "rb_str",
        Ty::Any => "rb_any",
        Ty::Int => "int32_t",
        Ty::Real => "double",
        Ty::Arr => "rb_array *",
        Ty::RetBuf(_) => "rb_any *",
    }
}

/// Saving a variable's value on the save stack (§8.3.1).
fn save(p: &Program, v: VarId) -> String {
    let var = &p.vars[v as usize];
    let d = if var.resident || var.kind == VarKind::AtPct { "NULL".to_string() } else { format!("&D{v}") };
    match var.kind {
        VarKind::AtPct => "rb_save_int(&rb_atpct, NULL);".to_string(),
        VarKind::Int => format!("rb_save_int(&V{v}, {d});"),
        VarKind::Real => format!("rb_save_real(&V{v}, {d});"),
        VarKind::Str => format!("rb_save_str(&V{v}, {d});"),
    }
}

/// The tables of names, lines and DATA (rb_program in rb_gen.h). EVAL, READ
/// and RESTORE use them.
fn tables(o: &mut String, p: &Program) {
    let cname = |n: &[u8]| String::from_utf8_lossy(n).replace('\\', "\\\\").replace('"', "\\\"");
    o.push_str("static const rb_sym SYMS[] = {\n");
    for (i, v) in p.vars.iter().enumerate() {
        let (kind, addr) = match v.kind {
            VarKind::Int => (0, format!("&V{i}")),
            VarKind::Real => (1, format!("&V{i}")),
            VarKind::Str => (2, format!("&V{i}")),
            VarKind::AtPct => (3, "NULL".to_string()),
        };
        let d = if v.resident || v.kind == VarKind::AtPct { "NULL".to_string() } else { format!("&D{i}") };
        let _ = writeln!(o, "    {{\"{}\", {}, {kind}, {addr}, {d}}},", cname(&v.name), v.name.len());
    }
    o.push_str("};\n");
    let arrays = if p.arrays.is_empty() {
        "NULL".to_string()
    } else {
        o.push_str("static const rb_asym ASYMS[] = {\n");
        for (i, a) in p.arrays.iter().enumerate() {
            let kind = match a.kind {
                VarKind::Int => 0,
                VarKind::Str => 2,
                _ => 1,
            };
            let _ = writeln!(o, "    {{\"{}\", {}, {kind}, &A{i}}},", cname(&a.name), a.name.len());
        }
        o.push_str("};\n");
        "ASYMS".to_string()
    };
    // A function that EVAL calls. FS saves its formals before EVAL
    // evaluates the arguments (§8.3.5). FT converts the arguments, last
    // first, and calls the function. EVAL cannot pass a RETURN or array
    // formal (error 31), so FT is never called with one.
    for f in &p.fns {
        let k = f.unit;
        let kinds: Vec<&str> = f
            .params
            .iter()
            .map(|q| match q {
                FnParam::Value(v) if p.vars[*v as usize].kind == VarKind::Str => "1",
                FnParam::Value(_) => "0",
                FnParam::Return(_) => "2",
                FnParam::Array => "3",
            })
            .collect();
        if !kinds.is_empty() {
            let _ = writeln!(o, "static const int32_t FK{k}[] = {{{}}};", kinds.join(", "));
        }
        let _ = writeln!(o, "static int32_t FS{k}(void)\n{{\n    int32_t m = rb_save_mark();");
        for q in &f.params {
            if let FnParam::Value(v) | FnParam::Return(v) = q {
                let _ = writeln!(o, "    {}", save(p, *v));
            }
        }
        let _ = writeln!(o, "    return m;\n}}");
        let _ = writeln!(o, "static rb_any FT{k}(int32_t m, const rb_any *args)\n{{");
        let u = &p.units[k];
        let mut call = vec!["m".to_string()];
        for (j, q) in f.params.iter().enumerate() {
            let ty = u.temps[j + 1];
            let _ = writeln!(o, "    {} a{j};", ctype(ty));
            call.push(format!("a{j}"));
            let _ = q;
        }
        if u.nparams > f.params.len() {
            call.push("NULL".to_string());
        }
        for (j, q) in f.params.iter().enumerate().rev() {
            let _ = match q {
                FnParam::Value(v) if p.vars[*v as usize].kind == VarKind::Str => writeln!(o, "    a{j} = rb_any_str(&args[{j}]);"),
                FnParam::Value(_) => writeln!(o, "    a{j} = rb_any_num(&args[{j}]);"),
                _ => writeln!(o, "    memset(&a{j}, 0, sizeof a{j});"),
            };
        }
        let _ = writeln!(o, "    return U{k}({});\n}}", call.join(", "));
    }
    let fns = if p.fns.is_empty() {
        "NULL".to_string()
    } else {
        o.push_str("static const rb_fsym FSYMS[] = {\n");
        for f in &p.fns {
            let k = f.unit;
            let pk = if f.params.is_empty() { "NULL".to_string() } else { format!("FK{k}") };
            let _ = writeln!(o, "    {{\"{}\", {}, {}, {pk}, FS{k}, FT{k}}},", cname(&f.name), f.name.len(), f.params.len());
        }
        o.push_str("};\n");
        "FSYMS".to_string()
    };
    let lines: Vec<String> = p.lines.iter().map(|n| n.to_string()).collect();
    let _ = writeln!(o, "static const uint16_t LINES[] = {{{}}};", if lines.is_empty() { "0".to_string() } else { lines.join(",") });
    let data = if p.data.is_empty() {
        "NULL".to_string()
    } else {
        for (j, (_, text)) in p.data.iter().enumerate() {
            let _ = writeln!(o, "static const uint8_t DT{j}[] = {{{}}};", if text.is_empty() { "0".to_string() } else { bytes(text) });
        }
        o.push_str("static const rb_dataline DATA[] = {\n");
        for (j, (line, text)) in p.data.iter().enumerate() {
            let _ = writeln!(o, "    {{{line}, DT{j}, {}}},", text.len());
        }
        o.push_str("};\n");
        "DATA".to_string()
    };
    let _ = writeln!(
        o,
        "static const rb_program PROG = {{SYMS, {}, {arrays}, {}, {fns}, {}, LINES, {}, {data}, {}}};\n",
        p.vars.len(),
        p.arrays.len(),
        p.fns.len(),
        p.lines.len(),
        p.data.len()
    );
}

fn signature(k: usize, u: &Unit) -> String {
    let ret = if u.kind == UnitKind::Fn { "rb_any" } else { "void" };
    if u.kind == UnitKind::Main {
        return format!("static void U{k}(void)");
    }
    let mut params = vec!["int32_t t0".to_string()];
    for i in 0..u.nparams {
        let t = u.temps[i + 1];
        params.push(format!("{} t{}", ctype(t), i + 1));
    }
    format!("static {ret} U{k}({})", params.join(", "))
}

fn unit(o: &mut String, p: &Program, k: usize, u: &Unit) {
    let name = String::from_utf8_lossy(&u.name);
    let _ = writeln!(o, "/* {} {} */", match u.kind {
        UnitKind::Main => "the main program",
        UnitKind::Proc => "PROC",
        UnitKind::Fn => "FN",
    }, name);
    let _ = writeln!(o, "{}\n{{", signature(k, u));
    let first = if u.kind == UnitKind::Main { 0 } else { 1 + u.nparams };
    for (i, t) in u.temps.iter().enumerate().skip(first) {
        match t {
            Ty::RetBuf(n) => {
                let _ = writeln!(o, "    rb_any t{i}[{n}];");
            }
            _ => {
                let _ = writeln!(o, "    {} t{i};", ctype(*t));
            }
        }
    }
    // A unit with handlers comes back to its jmp_buf. Anything that changes
    // after the setjmp and is needed after the longjmp must be volatile
    // (C99 7.13.2.1)
    let jb = !u.handlers.is_empty();
    let vol = if jb { "volatile " } else { "" };
    for (i, t) in u.slots.iter().enumerate() {
        let _ = writeln!(o, "    {vol}{} F{i};", ctype(*t));
    }
    if jb {
        o.push_str("    jmp_buf jb;\n");
    }
    if u.gosub {
        o.push_str("    int32_t rbase = rb_rstack_depth();\n");
    }
    let mut used = vec![false; u.blocks.len()];
    for blk in &u.blocks {
        match &blk.term {
            Term::Jump(b) => used[*b as usize] = true,
            Term::Branch(_, a, b) => {
                used[*a as usize] = true;
                used[*b as usize] = true;
            }
            Term::PopReturn(l) => l.iter().for_each(|(_, b)| used[*b as usize] = true),
            _ => {}
        }
    }
    for &h in &u.handlers {
        used[h as usize] = true;
    }
    for (b, blk) in u.blocks.iter().enumerate() {
        if used[b] {
            let _ = writeln!(o, "L{b}:;");
        }
        for i in &blk.insts {
            inst(o, p, i);
        }
        if b == 0 && jb {
            // After the prologue. An error comes back here and goes on to a
            // handler
            if u.kind == UnitKind::Main {
                o.push_str("    rb_main_jb(&jb);\n");
            }
            o.push_str("    switch (setjmp(jb)) {\n    case 0: break;\n");
            for (k, h) in u.handlers.iter().enumerate() {
                let _ = writeln!(o, "    case {}: goto L{h};", k + 1);
            }
            o.push_str("    }\n");
        }
        term(o, u, &blk.term);
    }
    o.push_str("}\n\n");
}

fn operand(o: &Operand, temps: &[Ty]) -> String {
    let _ = temps;
    match o {
        Operand::T(t) => match t.ty {
            Ty::Str | Ty::Any => format!("&t{}", t.id),
            _ => format!("t{}", t.id),
        },
        Operand::ArrSlot(a) => format!("&A{a}"),
        Operand::Imm(n) => format!("{n}"),
        Operand::Str(k) => format!("S{k}, sizeof S{k}"),
        Operand::Real(k) => format!("&R{k}"),
        Operand::Text(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        Operand::Jb => "&jb".to_string(),
        Operand::Arr(a) => format!("A{a}"),
        Operand::Asm(k) => format!("ASM{k}"),
        Operand::VarAddr(v) => format!("(int32_t)(intptr_t)&V{v}"),
        Operand::VarPtr(v) => format!("&V{v}"),
        Operand::Raw(s) => s.to_string(),
    }
}

fn args(v: &[Operand]) -> String {
    v.iter().map(|a| operand(a, &[])).collect::<Vec<_>>().join(", ")
}

fn load(p: &Program, v: VarId) -> String {
    let var = &p.vars[v as usize];
    match var.kind {
        VarKind::AtPct => "rb_i(rb_atpct)".to_string(),
        VarKind::Int if var.resident => format!("rb_i(V{v})"),
        VarKind::Int => format!("(D{v} ? rb_i(V{v}) : rb_undef_num())"),
        VarKind::Real => format!("(D{v} ? rb_r(V{v}) : rb_undef_num())"),
        VarKind::Str => format!("(D{v} ? V{v} : rb_undef_str())"),
    }
}

fn inst(o: &mut String, p: &Program, i: &Inst) {
    match i {
        // Each statement sets ERL and notices Escape (§9.2, §9.6.3)
        Inst::Line(n) => {
            let _ = writeln!(o, "    rb_erl = {n}; if (rb_escape_flag) rb_escape_raise();");
        }
        Inst::Let(t, rv) => {
            let r = match rv {
                Rv::Op(name, a) => {
                    // Strings come back by value. The empty-string literal
                    // is rb_s with no bytes
                    if *name == "rb_s" {
                        if let [Operand::Str(k)] = a.as_slice() {
                            if p.strs[*k as usize].is_empty() {
                                "rb_s(0, 0)".to_string()
                            } else {
                                format!("rb_s({})", operand(&a[0], &[]))
                            }
                        } else {
                            format!("{name}({})", args(a))
                        }
                    } else {
                        format!("{name}({})", args(a))
                    }
                }
                Rv::Load(v) => load(p, *v),
                Rv::Call(u, ts) => {
                    let a: Vec<String> = ts.iter().map(|t| format!("t{}", t.id)).collect();
                    format!("U{u}({})", a.join(", "))
                }
                Rv::Slot(s) => format!("F{s}"),
                Rv::Copy(op) => operand(op, &[]),
            };
            let _ = writeln!(o, "    t{} = {r};", t.id);
        }
        Inst::Do(name, a) => {
            let _ = writeln!(o, "    {name}({});", args(a));
        }
        Inst::Store(v, t) => {
            let var = &p.vars[*v as usize];
            let def = if var.resident || var.kind == VarKind::AtPct { String::new() } else { format!(" D{v} = 1;") };
            let _ = match var.kind {
                VarKind::AtPct => writeln!(o, "    rb_atpct = rb_toi(t{});", t.id),
                VarKind::Int => writeln!(o, "    V{v} = rb_toi(t{});{def}", t.id),
                VarKind::Real => writeln!(o, "    V{v} = rb_tor(t{});{def}", t.id),
                VarKind::Str => writeln!(o, "    V{v} = t{};{def}", t.id),
            };
        }
        Inst::Save(v, _) => {
            let _ = writeln!(o, "    {}", save(p, *v));
        }
        Inst::Restore(..) => {}
        Inst::Clear(v) => {
            let var = &p.vars[*v as usize];
            let def = if var.resident || var.kind == VarKind::AtPct { String::new() } else { format!(" D{v} = 1;") };
            let _ = match var.kind {
                VarKind::AtPct => writeln!(o, "    rb_atpct = 0;"),
                VarKind::Str => writeln!(o, "    V{v}.len = 0;{def}"),
                _ => writeln!(o, "    V{v} = 0;{def}"),
            };
        }
        Inst::SetLib(k) => {
            let _ = writeln!(o, "    rb_lib = {k};");
        }
        Inst::Create(v) => {
            let var = &p.vars[*v as usize];
            if !var.resident && var.kind != VarKind::AtPct {
                let z = if var.kind == VarKind::Str { format!("V{v}.len = 0") } else { format!("V{v} = 0") };
                let _ = writeln!(o, "    if (!D{v}) {{ {z}; D{v} = 1; }}");
            }
        }
        Inst::MustExist(v, n, m) => {
            let var = &p.vars[*v as usize];
            if !var.resident && var.kind != VarKind::AtPct {
                let _ = writeln!(o, "    if (!D{v}) rb_raise({n}, \"{m}\");");
            }
        }
        Inst::SaveArr(a) => {
            let _ = writeln!(o, "    rb_save_arr(&A{a});");
        }
        Inst::SetArr(a, t) => {
            let _ = writeln!(o, "    A{a} = t{};", t.id);
        }
        Inst::SetSlot(s, t) => {
            let _ = writeln!(o, "    F{s} = t{};", t.id);
        }
        Inst::CallProc(u, ts) => {
            let a: Vec<String> = ts.iter().map(|t| format!("t{}", t.id)).collect();
            let _ = writeln!(o, "    U{u}({});", a.join(", "));
        }
        Inst::PushReturn(k) => {
            let _ = writeln!(o, "    rb_rstack_push({k});");
        }
    }
}

fn term(o: &mut String, u: &Unit, t: &Term) {
    let _ = match t {
        Term::Jump(b) => writeln!(o, "    goto L{b};"),
        Term::Branch(c, a, b) => writeln!(o, "    if (t{}) goto L{a}; else goto L{b};", c.id),
        Term::PopReturn(list) => {
            o.push_str("    switch (rb_rstack_pop()) {\n");
            for (k, b) in list {
                let _ = writeln!(o, "    case {k}: goto L{b};");
            }
            writeln!(o, "    }}\n    rb_raise(38, \"Not in a subroutine\");")
        }
        Term::Return(None) => {
            if u.gosub {
                o.push_str("    rb_rstack_reset(rbase);\n");
            }
            writeln!(o, "    return;")
        }
        Term::Return(Some(v)) => {
            if u.gosub {
                o.push_str("    rb_rstack_reset(rbase);\n");
            }
            writeln!(o, "    return t{};", v.id)
        }
        Term::Raise(n, m) => writeln!(o, "    rb_raise({n}, \"{}\");", m.replace('"', "\\\"")),
        Term::End | Term::Open => writeln!(o, "    rb_end();"),
    };
}

/// Bytes as the inside of a C string literal. Every byte outside printable
/// ASCII, and the quotation mark and backslash, becomes an octal escape.
fn c_string(b: &[u8]) -> String {
    let mut s = String::new();
    for &c in b {
        if (0x20..0x7F).contains(&c) && c != b'"' && c != b'\\' && c != b'?' {
            s.push(c as char);
        } else {
            s.push_str(&format!("\\{:03o}", c));
        }
    }
    s
}
