//! BASIC's keyword table and token values, generated by tools/gentokens.py
//! from RISC OS's BASIC source (s/Lexical, hdr/Tokens; Apache 2.0, see NOTICE).
//! Do not edit: regenerate.

/// One entry of s/Lexical's keyword table, in the table's order (the
/// tokeniser takes the first entry that matches).
#[derive(Debug, Clone, Copy)]
pub struct Keyword {
    /// The keyword as it is spelt, with `(` where it is part of it.
    pub word: &'static str,
    /// The token byte (after the escape byte, for a two-byte token).
    pub token: u8,
    /// The job byte: how the tokeniser treats the keyword.
    pub job: u8,
}

pub const KEYWORDS: &[Keyword] = &[
    Keyword { word: "AND", token: 0x80, job: 0x02 },
    Keyword { word: "ABS", token: 0x94, job: 0x00 },
    Keyword { word: "ACS", token: 0x95, job: 0x00 },
    Keyword { word: "ADVAL", token: 0x96, job: 0x00 },
    Keyword { word: "ASC", token: 0x97, job: 0x00 },
    Keyword { word: "ASN", token: 0x98, job: 0x00 },
    Keyword { word: "ATN", token: 0x99, job: 0x00 },
    Keyword { word: "AUTO", token: 0x8F, job: 0x18 },
    Keyword { word: "APPEND", token: 0x8E, job: 0x0A },
    Keyword { word: "BGET", token: 0x9A, job: 0x01 },
    Keyword { word: "BPUT", token: 0xD5, job: 0x03 },
    Keyword { word: "BEATS", token: 0x9E, job: 0x4A },
    Keyword { word: "BEAT", token: 0x8F, job: 0x0E },
    Keyword { word: "COLOUR", token: 0xFB, job: 0x02 },
    Keyword { word: "CALL", token: 0xD6, job: 0x02 },
    Keyword { word: "CASE", token: 0x8E, job: 0x4A },
    Keyword { word: "CHAIN", token: 0xD7, job: 0x02 },
    Keyword { word: "CHR$", token: 0xBD, job: 0x00 },
    Keyword { word: "CLEAR", token: 0xD8, job: 0x01 },
    Keyword { word: "CLOSE", token: 0xD9, job: 0x03 },
    Keyword { word: "CLG", token: 0xDA, job: 0x01 },
    Keyword { word: "CLS", token: 0xDB, job: 0x01 },
    Keyword { word: "COS", token: 0x9B, job: 0x00 },
    Keyword { word: "COUNT", token: 0x9C, job: 0x01 },
    Keyword { word: "CIRCLE", token: 0x8F, job: 0x4A },
    Keyword { word: "CRUNCH", token: 0x90, job: 0x0A },
    Keyword { word: "COLOR", token: 0xFB, job: 0x02 },
    Keyword { word: "DATA", token: 0xDC, job: 0x20 },
    Keyword { word: "DEG", token: 0x9D, job: 0x00 },
    Keyword { word: "DEF", token: 0xDD, job: 0x00 },
    Keyword { word: "DELETE", token: 0x91, job: 0x18 },
    Keyword { word: "DIV", token: 0x81, job: 0x00 },
    Keyword { word: "DIM", token: 0xDE, job: 0x02 },
    Keyword { word: "DRAW", token: 0xDF, job: 0x02 },
    Keyword { word: "ENDPROC", token: 0xE1, job: 0x01 },
    Keyword { word: "EDIT", token: 0x92, job: 0x28 },
    Keyword { word: "ENDWHILE", token: 0xCE, job: 0x01 },
    Keyword { word: "ENDCASE", token: 0xCB, job: 0x01 },
    Keyword { word: "ENDIF", token: 0xCD, job: 0x01 },
    Keyword { word: "END", token: 0xE0, job: 0x01 },
    Keyword { word: "ENVELOPE", token: 0xE2, job: 0x02 },
    Keyword { word: "ELSE", token: 0x8B, job: 0x14 },
    Keyword { word: "EVAL", token: 0xA0, job: 0x00 },
    Keyword { word: "ERL", token: 0x9E, job: 0x01 },
    Keyword { word: "ERROR", token: 0x85, job: 0x04 },
    Keyword { word: "EOF", token: 0xC5, job: 0x01 },
    Keyword { word: "EOR", token: 0x82, job: 0x02 },
    Keyword { word: "ERR", token: 0x9F, job: 0x01 },
    Keyword { word: "EXP", token: 0xA1, job: 0x00 },
    Keyword { word: "EXT", token: 0xA2, job: 0x01 },
    Keyword { word: "ELLIPSE", token: 0x9D, job: 0x4A },
    Keyword { word: "FOR", token: 0xE3, job: 0x02 },
    Keyword { word: "FALSE", token: 0xA3, job: 0x01 },
    Keyword { word: "FILL", token: 0x90, job: 0x4A },
    Keyword { word: "FN", token: 0xA4, job: 0x02 },
    Keyword { word: "GOTO", token: 0xE5, job: 0x12 },
    Keyword { word: "GET$", token: 0xBE, job: 0x00 },
    Keyword { word: "GET", token: 0xA5, job: 0x00 },
    Keyword { word: "GOSUB", token: 0xE4, job: 0x12 },
    Keyword { word: "GCOL", token: 0xE6, job: 0x02 },
    Keyword { word: "HIMEM", token: 0x93, job: 0x43 },
    Keyword { word: "HELP", token: 0x93, job: 0x09 },
    Keyword { word: "INPUT", token: 0xE8, job: 0x02 },
    Keyword { word: "IF", token: 0xE7, job: 0x02 },
    Keyword { word: "INKEY$", token: 0xBF, job: 0x00 },
    Keyword { word: "INKEY", token: 0xA6, job: 0x00 },
    Keyword { word: "INT", token: 0xA8, job: 0x00 },
    Keyword { word: "INSTR(", token: 0xA7, job: 0x80 },
    Keyword { word: "INSTALL", token: 0x9F, job: 0x0A },
    Keyword { word: "LIST", token: 0x94, job: 0x18 },
    Keyword { word: "LINE", token: 0x86, job: 0x02 },
    Keyword { word: "LOAD", token: 0x95, job: 0x0A },
    Keyword { word: "LOMEM", token: 0x92, job: 0x43 },
    Keyword { word: "LOCAL", token: 0xEA, job: 0x02 },
    Keyword { word: "LEFT$(", token: 0xC0, job: 0x80 },
    Keyword { word: "LEN", token: 0xA9, job: 0x00 },
    Keyword { word: "LET", token: 0xE9, job: 0x04 },
    Keyword { word: "LOG", token: 0xAB, job: 0x00 },
    Keyword { word: "LN", token: 0xAA, job: 0x00 },
    Keyword { word: "LIBRARY", token: 0x9B, job: 0x4A },
    Keyword { word: "LVAR", token: 0x96, job: 0x09 },
    Keyword { word: "MID$(", token: 0xC1, job: 0x80 },
    Keyword { word: "MODE", token: 0xEB, job: 0x02 },
    Keyword { word: "MOD", token: 0x83, job: 0x00 },
    Keyword { word: "MOVE", token: 0xEC, job: 0x02 },
    Keyword { word: "MOUSE", token: 0x97, job: 0x4A },
    Keyword { word: "NEXT", token: 0xED, job: 0x02 },
    Keyword { word: "NEW", token: 0x97, job: 0x09 },
    Keyword { word: "NOT", token: 0xAC, job: 0x00 },
    Keyword { word: "OLD", token: 0x98, job: 0x09 },
    Keyword { word: "ON", token: 0xEE, job: 0x02 },
    Keyword { word: "OFF", token: 0x87, job: 0x00 },
    Keyword { word: "OF", token: 0xCA, job: 0x00 },
    Keyword { word: "ORIGIN", token: 0x91, job: 0x4A },
    Keyword { word: "OR", token: 0x84, job: 0x02 },
    Keyword { word: "OPENIN", token: 0x8E, job: 0x00 },
    Keyword { word: "OPENOUT", token: 0xAE, job: 0x00 },
    Keyword { word: "OPENUP", token: 0xAD, job: 0x00 },
    Keyword { word: "OSCLI", token: 0xFF, job: 0x02 },
    Keyword { word: "OTHERWISE", token: 0x7F, job: 0x04 },
    Keyword { word: "OVERLAY", token: 0xA3, job: 0x4A },
    Keyword { word: "PRINT", token: 0xF1, job: 0x02 },
    Keyword { word: "PAGE", token: 0x90, job: 0x43 },
    Keyword { word: "PTR", token: 0x8F, job: 0x43 },
    Keyword { word: "PI", token: 0xAF, job: 0x01 },
    Keyword { word: "PLOT", token: 0xF0, job: 0x02 },
    Keyword { word: "POINT(", token: 0xB0, job: 0x80 },
    Keyword { word: "POINT", token: 0x92, job: 0x4A },
    Keyword { word: "PROC", token: 0xF2, job: 0x02 },
    Keyword { word: "POS", token: 0xB1, job: 0x01 },
    Keyword { word: "QUIT", token: 0x98, job: 0x4A },
    Keyword { word: "RETURN", token: 0xF8, job: 0x01 },
    Keyword { word: "REPEAT", token: 0xF5, job: 0x00 },
    Keyword { word: "REPORT", token: 0xF6, job: 0x01 },
    Keyword { word: "READ", token: 0xF3, job: 0x02 },
    Keyword { word: "REM", token: 0xF4, job: 0x20 },
    Keyword { word: "RUN", token: 0xF9, job: 0x01 },
    Keyword { word: "RAD", token: 0xB2, job: 0x00 },
    Keyword { word: "RESTORE", token: 0xF7, job: 0x12 },
    Keyword { word: "RIGHT$(", token: 0xC2, job: 0x80 },
    Keyword { word: "RND", token: 0xB3, job: 0x01 },
    Keyword { word: "RECTANGLE", token: 0x93, job: 0x4A },
    Keyword { word: "RENUMBER", token: 0x99, job: 0x18 },
    Keyword { word: "STEP", token: 0x88, job: 0x00 },
    Keyword { word: "SAVE", token: 0x9A, job: 0x0A },
    Keyword { word: "SGN", token: 0xB4, job: 0x00 },
    Keyword { word: "SIN", token: 0xB5, job: 0x00 },
    Keyword { word: "SQR", token: 0xB6, job: 0x00 },
    Keyword { word: "SOUND", token: 0xD4, job: 0x02 },
    Keyword { word: "SPC", token: 0x89, job: 0x00 },
    Keyword { word: "STR$", token: 0xC3, job: 0x00 },
    Keyword { word: "STRING$(", token: 0xC4, job: 0x80 },
    Keyword { word: "STOP", token: 0xFA, job: 0x01 },
    Keyword { word: "STEREO", token: 0xA2, job: 0x4A },
    Keyword { word: "SUM", token: 0x8E, job: 0x0E },
    Keyword { word: "SWAP", token: 0x94, job: 0x4A },
    Keyword { word: "SYS", token: 0x99, job: 0x4A },
    Keyword { word: "TAN", token: 0xB7, job: 0x00 },
    Keyword { word: "TAB(", token: 0x8A, job: 0x80 },
    Keyword { word: "TEMPO", token: 0x9F, job: 0x4A },
    Keyword { word: "TEXTLOAD", token: 0x9B, job: 0x0A },
    Keyword { word: "TEXTSAVE", token: 0x9C, job: 0x0A },
    Keyword { word: "THEN", token: 0x8C, job: 0x14 },
    Keyword { word: "TIME", token: 0x91, job: 0x43 },
    Keyword { word: "TINT", token: 0x9C, job: 0x4A },
    Keyword { word: "TO", token: 0xB8, job: 0x00 },
    Keyword { word: "TRACE", token: 0xFC, job: 0x12 },
    Keyword { word: "TRUE", token: 0xB9, job: 0x01 },
    Keyword { word: "TWINO", token: 0x9E, job: 0x0A },
    Keyword { word: "TWIN", token: 0x9D, job: 0x09 },
    Keyword { word: "UNTIL", token: 0xFD, job: 0x02 },
    Keyword { word: "USR", token: 0xBA, job: 0x00 },
    Keyword { word: "VDU", token: 0xEF, job: 0x02 },
    Keyword { word: "VAL", token: 0xBB, job: 0x00 },
    Keyword { word: "VPOS", token: 0xBC, job: 0x01 },
    Keyword { word: "VOICES", token: 0xA0, job: 0x4A },
    Keyword { word: "VOICE", token: 0xA1, job: 0x4A },
    Keyword { word: "WHILE", token: 0x95, job: 0x4A },
    Keyword { word: "WHEN", token: 0xC9, job: 0x02 },
    Keyword { word: "WAIT", token: 0x96, job: 0x49 },
    Keyword { word: "WIDTH", token: 0xFE, job: 0x02 },
];

// Token values from hdr/Tokens.
pub const TOTHER: u8 = 0x7F;
pub const TAND: u8 = 0x80;
pub const TDIV: u8 = 0x81;
pub const TEOR: u8 = 0x82;
pub const TMOD: u8 = 0x83;
pub const TOR: u8 = 0x84;
pub const TERROR: u8 = 0x85;
pub const TLINE: u8 = 0x86;
pub const TOFF: u8 = 0x87;
pub const TSTEP: u8 = 0x88;
pub const TSPC: u8 = 0x89;
pub const TTAB: u8 = 0x8A;
pub const TELSE: u8 = 0x8B;
pub const TTHEN: u8 = 0x8C;
pub const TCONST: u8 = 0x8D;
pub const TAPPEND: u8 = 0x8E;
pub const TCASE: u8 = 0x8E;
pub const TOPENU: u8 = 0x8E;
pub const TSUM: u8 = 0x8E;
pub const TAUTO: u8 = 0x8F;
pub const TBEAT: u8 = 0x8F;
pub const TCIRCLE: u8 = 0x8F;
pub const TPTR: u8 = 0x8F;
pub const TCRUNCH: u8 = 0x90;
pub const TFILL: u8 = 0x90;
pub const TPAGE: u8 = 0x90;
pub const TTWOFUNCLIMIT: u8 = 0x90;
pub const TDELET: u8 = 0x91;
pub const TORGIN: u8 = 0x91;
pub const TTIME: u8 = 0x91;
pub const TEDIT: u8 = 0x92;
pub const TLOMEM: u8 = 0x92;
pub const TPSET: u8 = 0x92;
pub const THELP: u8 = 0x93;
pub const THIMEM: u8 = 0x93;
pub const TRECT: u8 = 0x93;
pub const TABS: u8 = 0x94;
pub const TLIST: u8 = 0x94;
pub const TSWAP: u8 = 0x94;
pub const TACS: u8 = 0x95;
pub const TLOAD: u8 = 0x95;
pub const TWHILE: u8 = 0x95;
pub const TADC: u8 = 0x96;
pub const TLVAR: u8 = 0x96;
pub const TWAIT: u8 = 0x96;
pub const TASC: u8 = 0x97;
pub const TMOUSE: u8 = 0x97;
pub const TNEW: u8 = 0x97;
pub const TASN: u8 = 0x98;
pub const TOLD: u8 = 0x98;
pub const TQUIT: u8 = 0x98;
pub const TATN: u8 = 0x99;
pub const TRENUM: u8 = 0x99;
pub const TSYS: u8 = 0x99;
pub const TBGET: u8 = 0x9A;
pub const TINSTALLBAD: u8 = 0x9A;
pub const TSAVE: u8 = 0x9A;
pub const TCOS: u8 = 0x9B;
pub const TLIBRARY: u8 = 0x9B;
pub const TTEXTLOAD: u8 = 0x9B;
pub const TCOUNT: u8 = 0x9C;
pub const TTEXTSAVE: u8 = 0x9C;
pub const TTINT: u8 = 0x9C;
pub const TDEG: u8 = 0x9D;
pub const TELLIPSE: u8 = 0x9D;
pub const TTWIN: u8 = 0x9D;
pub const TBEATS: u8 = 0x9E;
pub const TERL: u8 = 0x9E;
pub const TTWINO: u8 = 0x9E;
pub const TERR: u8 = 0x9F;
pub const TINSTALL: u8 = 0x9F;
pub const TTEMPO: u8 = 0x9F;
pub const TEVAL: u8 = 0xA0;
pub const TTWOCOMMLIMIT: u8 = 0xA0;
pub const TVOICES: u8 = 0xA0;
pub const TEXP: u8 = 0xA1;
pub const TVOICE: u8 = 0xA1;
pub const TEXT: u8 = 0xA2;
pub const TSTEREO: u8 = 0xA2;
pub const TFALSE: u8 = 0xA3;
pub const TOVERLAY: u8 = 0xA3;
pub const TFN: u8 = 0xA4;
pub const TTWOSTMTLIMIT: u8 = 0xA4;
pub const TGET: u8 = 0xA5;
pub const TINKEY: u8 = 0xA6;
pub const TINSTR: u8 = 0xA7;
pub const TINT: u8 = 0xA8;
pub const TLEN: u8 = 0xA9;
pub const TLN: u8 = 0xAA;
pub const TLOG: u8 = 0xAB;
pub const TNOT: u8 = 0xAC;
pub const TOPENI: u8 = 0xAD;
pub const TOPENO: u8 = 0xAE;
pub const TPI: u8 = 0xAF;
pub const TPOINT: u8 = 0xB0;
pub const TPOS: u8 = 0xB1;
pub const TRAD: u8 = 0xB2;
pub const TRND: u8 = 0xB3;
pub const TSGN: u8 = 0xB4;
pub const TSIN: u8 = 0xB5;
pub const TSQR: u8 = 0xB6;
pub const TTAN: u8 = 0xB7;
pub const TTO: u8 = 0xB8;
pub const TTRUE: u8 = 0xB9;
pub const TUSR: u8 = 0xBA;
pub const TVAL: u8 = 0xBB;
pub const TVPOS: u8 = 0xBC;
pub const TCHRD: u8 = 0xBD;
pub const TGETD: u8 = 0xBE;
pub const TINKED: u8 = 0xBF;
pub const TLEFTD: u8 = 0xC0;
pub const TMIDD: u8 = 0xC1;
pub const TRIGHTD: u8 = 0xC2;
pub const TSTRD: u8 = 0xC3;
pub const TSTRND: u8 = 0xC4;
pub const TEOF: u8 = 0xC5;
pub const TESCFN: u8 = 0xC6;
pub const TESCCOM: u8 = 0xC7;
pub const TESCSTMT: u8 = 0xC8;
pub const TWHEN: u8 = 0xC9;
pub const TOF: u8 = 0xCA;
pub const TENDCA: u8 = 0xCB;
pub const TELSE2: u8 = 0xCC;
pub const TENDIF: u8 = 0xCD;
pub const TENDWH: u8 = 0xCE;
pub const TPTR2: u8 = 0xCF;
pub const TPAGE2: u8 = 0xD0;
pub const TTIME2: u8 = 0xD1;
pub const TLOMM2: u8 = 0xD2;
pub const THIMM2: u8 = 0xD3;
pub const TBEEP: u8 = 0xD4;
pub const TBPUT: u8 = 0xD5;
pub const TCALL: u8 = 0xD6;
pub const TCHAIN: u8 = 0xD7;
pub const TCLEAR: u8 = 0xD8;
pub const TCLOSE: u8 = 0xD9;
pub const TCLG: u8 = 0xDA;
pub const TCLS: u8 = 0xDB;
pub const TDATA: u8 = 0xDC;
pub const TDEF: u8 = 0xDD;
pub const TDIM: u8 = 0xDE;
pub const TDRAW: u8 = 0xDF;
pub const TEND: u8 = 0xE0;
pub const TENDPR: u8 = 0xE1;
pub const TENVEL: u8 = 0xE2;
pub const TFOR: u8 = 0xE3;
pub const TGOSUB: u8 = 0xE4;
pub const TGOTO: u8 = 0xE5;
pub const TGRAPH: u8 = 0xE6;
pub const TIF: u8 = 0xE7;
pub const TINPUT: u8 = 0xE8;
pub const TLET: u8 = 0xE9;
pub const TLOCAL: u8 = 0xEA;
pub const TMODE: u8 = 0xEB;
pub const TMOVE: u8 = 0xEC;
pub const TNEXT: u8 = 0xED;
pub const TON: u8 = 0xEE;
pub const TVDU: u8 = 0xEF;
pub const TPLOT: u8 = 0xF0;
pub const TPRINT: u8 = 0xF1;
pub const TPROC: u8 = 0xF2;
pub const TREAD: u8 = 0xF3;
pub const TREM: u8 = 0xF4;
pub const TREPEAT: u8 = 0xF5;
pub const TREPORT: u8 = 0xF6;
pub const TRESTORE: u8 = 0xF7;
pub const TRETURN: u8 = 0xF8;
pub const TRUN: u8 = 0xF9;
pub const TSTOP: u8 = 0xFA;
pub const TTEXT: u8 = 0xFB;
pub const TTRACE: u8 = 0xFC;
pub const TUNTIL: u8 = 0xFD;
pub const TWIDTH: u8 = 0xFE;
pub const TOSCL: u8 = 0xFF;
