#!/usr/bin/env python3
"""bin2c.py OUT.h NAME=FILE... -- files as C byte arrays, for the self-test
(boot/selftest_capps.c carries the C application probes it runs):

    static const unsigned char NAME[] = { ... };
    #define NAME_SIZE <bytes>
"""
import sys


def main(argv):
    out, pairs = argv[1], argv[2:]
    lines = ["/* generated by tools/bin2c.py: do not edit */"]
    for pair in pairs:
        name, path = pair.split("=", 1)
        data = open(path, "rb").read()
        lines.append(f"static const unsigned char {name}[] __attribute__((unused, aligned(16))) = {{")
        for i in range(0, len(data), 16):
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
        lines.append("};")
        lines.append(f"#define {name.upper()}_SIZE {len(data)}u")
    open(out, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(sys.argv)
