"""capps_headers.py -- the staged headers as a client includes them (packages T4b and Q1).

make capps stages headers for clients: OUT/inc (C:, RISCOSLIB:, tbox:, OS:)
and the applications' and the Toolbox's own h/ files under OUT/src.  The
source pass (tools/capps_pass.py) edits only what a unit it parses reaches,
and the built units (the library, rlib, the Toolbox) reach a fraction of
them: without more, a client of oslib/wimp.h or of Draw's h/ files would get
clang's layouts, not Norcroft's.  So every staged client header belongs to a
group:

  a group is one translation unit, OUT/hdrunits/<name>.c, that includes the
  group's headers in order, each after the headers its users include before
  it, with the group's include path.  The pass parses each group as a unit
  (capps.py stage adds them to its units; rules.mk builds none of them), and
  Q1's layout probes (tests/capps/layout) measure the records defined in the
  group's directories, from the same unit, on the farm and for x32.

A header that parses on its own needs nothing before it.  One that does not
gets the #include lines that come before it in a staged file that includes
it (a "user"), or failing that in a user of a twin (the same file staged in
another place: rlib's h/ is src/Lib/RISC_OSLib/rlib and inc/RISCOSLIB, and
ToolboxLib's is inc/tbox and inc/C/tboxlibs), the first whose lines make it
parse, or failing that one of a few common contexts (kernel.h; OSLib's
os.h).  A header that parses in no context is excluded, with clang's error
as the reason; make capps prints the list, and Q1's compare fails unless
its known.txt lists each with the reason.  A header that parses but breaks
its group's unit (a clash) gets a group of its own ("<group>.<n>").

The libraries exported to C: are staged whole, but a client on RISC OS sees
only what each exports (its Makefile's HDRS): their groups are those, and
what those include.

The groups are worked out when the staged tree changes and kept in
OUT/hdrgroups.json, keyed by the staged files, the compiler and flags, and
this file.  Paths in it are OUT-relative.
"""
import collections
import concurrent.futures
import functools
import hashlib
import json
import os
import re
import subprocess

# The applications whose h/ files are staged for clients (proposal revision 3,
# phase 3): OUT/src/Apps/<name>, from Sources/<where>.  Their Makefiles put
# RISCOSLIB: on the path after their own directory (Help reaches ToolboxLib
# as C:'s "tboxlibs/...").
APPS = collections.OrderedDict([
    ("Draw", "Apps/Draw"),
    ("Edit", "Apps/EditApp"),
    ("Paint", "Apps/Paint"),
    ("FilerAct", "Desktop/FilerAct"),
    ("Help", "Apps/Help2"),
])

C_PATH = ["inc/C", "inc/RISCOSLIB"]           # C: as capps.py's c_path has it
TBOX_PATH = ["inc/tbox"] + C_PATH              # -Itbox:,C:
OS_PATH = ["inc/OS"] + C_PATH                  # -IOS:,C:

# Staged under h/ but not C: each with why.
NOT_HEADERS = {
    "inc/RISCOSLIB/README.h": "rlib's h.README is a text file, not C",
}

# Tried, in order, for a header that parses neither alone nor after any
# user's lines (none includes it): the kernel's types, then OSLib's
COMMON_PRELUDES = [["kernel.h"], ["kernel.h", "swis.h"], ["oslib/types.h", "oslib/os.h"],
                   ["kernel.h", "os.h", "wimp.h"]]

_INCLUDE = re.compile(r'^[ \t]*#[ \t]*include[ \t]*([<"])([^>"]+)[>"]', re.M)


class Group:
    """name; path: the include path (OUT-relative directories, in order);
    headers: the group's own headers; lines: the unit's #include names, in
    order; dirs: where the records Q1 measures are defined ("d/*" the files
    in d, "d/**" and those under it)."""

    def __init__(self, name, path, headers, lines=None, dirs=None):
        self.name, self.path, self.headers = name, list(path), list(headers)
        self.lines, self.dirs = list(lines or []), list(dirs or [])

    def to_json(self):
        return {"name": self.name, "path": self.path, "headers": self.headers, "lines": self.lines,
                "dirs": self.dirs}

    @staticmethod
    def from_json(d):
        return Group(d["name"], d["path"], d["headers"], d["lines"], d["dirs"])

    def owns(self, rel):
        """Is an OUT-relative file in the group's directories?"""
        for d in self.dirs:
            base, how = d.rsplit("/", 1)
            if how == "**" and rel.startswith(base + "/"):
                return True
            if how == "*" and os.path.dirname(rel) == base:
                return True
        return False

    def unit_text(self):
        return ("/* %s -- generated by tools/capps_headers.py: the staged headers of group\n"
                " * %s, each after what its users include before it (a unit of the source\n"
                " * pass; Q1's layout probe of the group is this and its tables). */\n"
                % (self.name, self.name) + "".join('#include "%s"\n' % n for n in self.lines))


def _hfiles(out, d, recursive):
    base = os.path.join(out, d)
    res = []
    if not os.path.isdir(base):
        return res
    if recursive:
        for dp, dn, fn in os.walk(base):
            dn.sort()
            res += [os.path.relpath(os.path.join(dp, f), out) for f in sorted(fn) if f.endswith(".h")]
    else:
        res = [os.path.join(d, f) for f in sorted(os.listdir(base))
               if f.endswith(".h") and os.path.isfile(os.path.join(base, f))]
    return res


def _dedup(xs):
    res = []
    for x in xs:
        if x not in res:
            res.append(x)
    return res


def specs(out, libs, toolbox):
    """The groups before discovery: [(name, include path, own headers, dirs)].
    out: the tree to look in (OUT/pre).  libs: {library exported to C:
    (capps.py's C_EXPORTS): (its include path, its exported headers, or None
    for all)}.  toolbox: {src/Toolbox/X: the include path of X's units}."""
    res = []
    top = [h for h in _hfiles(out, "inc/C", False) if h != "inc/C/ToolAction.h"]
    res.append(("clib", C_PATH, top, ["inc/C/*"]))
    res.append(("global", C_PATH, _hfiles(out, "inc/C/Global", True) + _hfiles(out, "inc/C/Interface", True),
                ["inc/C/Global/**", "inc/C/Interface/**"]))
    for lib in sorted(libs, key=str.lower):
        path, hdrs = libs[lib]
        d = "inc/C/" + lib
        allh = _hfiles(out, d, True)
        own = allh if hdrs is None else [h for h in hdrs if h in allh]
        res.append((lib.lower(), _dedup(path + C_PATH + [d]), own, [d + "/**"]))
    res.append(("tboxlibs", C_PATH, _hfiles(out, "inc/C/tboxlibs", True), ["inc/C/tboxlibs/**"]))
    res.append(("rlib", C_PATH, _hfiles(out, "inc/RISCOSLIB", False), ["inc/RISCOSLIB/*"]))
    res.append(("tbox", TBOX_PATH, _hfiles(out, "inc/tbox", False), ["inc/tbox/*"]))
    if os.path.isfile(os.path.join(out, "inc/C/ToolAction.h")):
        # DefMod's header for ToolAction, which its Makefile exports to C:
        res.append(("toolaction", _dedup(toolbox.get("src/Toolbox/ToolAction", []) + OS_PATH + TBOX_PATH),
                    ["inc/C/ToolAction.h"], []))
    res.append(("oslib", OS_PATH, _hfiles(out, "inc/OS/oslib", False), ["inc/OS/oslib/*"]))
    res.append(("os", OS_PATH, _hfiles(out, "inc/OS", False), ["inc/OS/*"]))
    for name in APPS:
        d = "src/Apps/" + name
        res.append((name.lower(), [d] + C_PATH, _hfiles(out, d, True), [d + "/**"]))
    tb = os.path.join(out, "src", "Toolbox")
    if os.path.isdir(tb):
        for m in sorted(os.listdir(tb)):
            d = "src/Toolbox/" + m
            hs = _hfiles(out, d, True)
            if not hs:
                continue
            # every unit's path in the component, then each header's directory
            path = []
            for k, p in sorted(toolbox.items()):
                if k == d or k.startswith(d + "/"):
                    path += p
            path = _dedup((path or [d] + TBOX_PATH) + sorted({os.path.dirname(h) for h in hs}))
            res.append(("toolbox-" + m.lower(), path, hs, [d + "/**"]))
    return [(n, p, [h for h in hs if h not in NOT_HEADERS], ds) for n, p, hs, ds in res if hs]


# ---------------------------------------------------------------------------
# discovery

def _includes(path):
    try:
        with open(path, "rb") as f:
            t = f.read().decode("latin-1")
    except OSError:
        return []
    return [m.group(2).strip() for m in _INCLUDE.finditer(t)]


@functools.lru_cache(maxsize=None)
def _isfile(p):
    return os.path.isfile(p)


def _resolve(name, where, path, out):
    """An include name -> OUT-relative file, searched from the including
    file's directory (where, OUT-relative) and then the path."""
    for d in ([where] if where is not None else []) + list(path):
        p = os.path.normpath(os.path.join(d, name))
        if _isfile(os.path.join(out, p)):
            return p
    return None


def _canonical(rel, path):
    """The name a unit with this include path includes an OUT-relative file by."""
    for d in path:
        if rel.startswith(d + "/"):
            return rel[len(d) + 1:]
    return None


class _Clang:
    def __init__(self, cc, cflags, out, tmp):
        self.cc, self.cflags, self.out, self.tmp = cc, cflags, out, tmp
        os.makedirs(tmp, exist_ok=True)

    def parses(self, path, lines, tag):
        """None if the unit parses, else clang's first error."""
        src = os.path.join(self.tmp, tag + ".c")
        with open(src, "w") as f:
            f.write("".join('#include "%s"\n' % n for n in lines))
        argv = self.cc + self.cflags + ["-I" + os.path.join(self.out, d) for d in path] + \
            ["-w", "-fsyntax-only", src]
        r = subprocess.run(argv, capture_output=True, text=True, errors="replace")
        if r.returncode == 0:
            return None
        errs = [l for l in r.stderr.split("\n") if "error:" in l]
        e = errs[0] if errs else r.stderr.strip().split("\n")[-1]
        return e.replace(self.out + "/", "").replace(self.tmp + "/", "")


def discover(out, group_specs, cc, cflags, users, jobs, tmp):
    """Each header's prelude, then the groups' units.  users: every staged
    file (OUT-relative) whose #include lines count.
    -> ([Group], {header: reason excluded})"""
    clang = _Clang(cc, cflags, out, tmp)
    inc_of = {u: _includes(os.path.join(out, u)) for u in users}
    roots = _dedup([d for _, p, _, _ in group_specs for d in p])
    digest = {}
    for u in users:
        with open(os.path.join(out, u), "rb") as f:
            digest[u] = hashlib.sha256(f.read()).hexdigest()
    by_digest = collections.defaultdict(list)
    for u, d in digest.items():
        by_digest[d].append(u)

    def preludes(h, path):
        """Candidate preludes for h: (rank, user, [include names in path])"""
        cands = []
        twins = [t for t in by_digest.get(digest.get(h), []) if t != h and os.path.basename(t) == os.path.basename(h)]
        for target, rank in [(h, 0)] + [(t, 2) for t in sorted(twins)]:
            tdir, hdir = os.path.dirname(target), os.path.dirname(h)
            # a twin's users are resolved as its own context has them
            upath = path if target == h else _dedup([tdir] + path + roots)
            for u in users:
                names = inc_of[u]
                where = os.path.dirname(u)
                for i, n in enumerate(names):
                    if _resolve(n, where, upath, out) != target:
                        continue
                    pre = []
                    for m in names[:i]:
                        r = _resolve(m, where, upath, out)
                        if r and target != h and r.startswith(tdir + "/"):
                            moved = hdir + r[len(tdir):]
                            r = moved if os.path.isfile(os.path.join(out, moved)) else None
                        c = _canonical(r, path) if r else None
                        if c is None:
                            pre = None
                            break
                        if c not in pre:
                            pre.append(c)
                    if pre is not None:
                        near = os.path.commonpath([tdir, where]) == tdir
                        cands.append((rank + (0 if near else 1), u, pre))
                    break
        return sorted(cands)

    def prelude_for(args):
        gname, path, h, k = args
        own = _canonical(h, path)
        if own is None:
            return h, None, "not under the group's include path"
        err = clang.parses(path, [own], "%s-%d" % (gname, k))
        if err is None:
            return h, [own], None
        seen, tried = set(), []
        for _, u, pre in preludes(h, path):
            key = tuple(pre)
            if key in seen or not pre:
                continue
            seen.add(key)
            e2 = clang.parses(path, pre + [own], "%s-%d" % (gname, k))
            if e2 is None:
                return h, pre + [own], None
            tried.append("after %s's includes: %s" % (u, e2))
            if len(seen) >= 12:
                break
        # no user's lines: the contexts RISC OS C most often assumes
        for pre in COMMON_PRELUDES:
            pre = [n for n in pre if _resolve(n, None, path, out)]
            if pre and tuple(pre) not in seen:
                seen.add(tuple(pre))
                if clang.parses(path, pre + [own], "%s-%d" % (gname, k)) is None:
                    return h, pre + [own], None
        return h, None, "; ".join([err] + tried[:2])

    work = [(g, p, h, i) for gi, (g, p, hs, _) in enumerate(group_specs) for i, h in enumerate(hs)]
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as ex:
        found = {h: (lines, err) for h, lines, err in ex.map(prelude_for, work)}
    excluded = {}

    def build(name, path, hs, dirs):
        lines, own = [], []
        for h in hs:
            ls, err = found[h]
            if ls is None:
                excluded[h] = err
                continue
            for n in ls:
                if n not in lines:
                    lines.append(n)
            own.append(h)
        return Group(name, path, own, lines, dirs)

    def split(g):
        """A group whose unit does not parse: the longest run of its headers
        that parses stays (found by bisection); the header that ends the run
        goes to a group of its own; the rest are tried after the run."""
        def ok(hs):
            return clang.parses(g.path, build(g.name, g.path, hs, g.dirs).lines, g.name + "-split") is None
        base, alone, rest = [], [], list(g.headers)
        while rest:
            if ok(base + rest):
                base += rest
                break
            lo, hi = 0, len(rest)          # base + rest[:lo] parses, base + rest[:hi] does not
            while hi - lo > 1:
                mid = (lo + hi) // 2
                if ok(base + rest[:mid]):
                    lo = mid
                else:
                    hi = mid
            base += rest[:lo]
            alone.append(rest[lo])
            rest = rest[lo + 1:]
        res = [build(g.name, g.path, base, g.dirs)] if base else []
        for i, h in enumerate(alone):
            res.append(build("%s.%d" % (g.name, i + 1), g.path, [h], [h.rsplit("/", 1)[0] + "/*"]))
        return res

    todo = [build(n, p, hs, ds) for n, p, hs, ds in group_specs]
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as ex:
        ok = list(ex.map(lambda g: g.headers and clang.parses(g.path, g.lines, g.name + "-all") is None, todo))
    groups = []
    for g, good in zip(todo, ok):
        if g.headers:
            groups += [g] if good else split(g)
    return groups, excluded


def groups(out, pre, cc, cflags, libs, toolbox, jobs, staged):
    """The groups for the tree staged in pre (OUT/pre), cached in
    OUT/hdrgroups.json; each group's unit is written to OUT/hdrunits/.
    staged: every staged path (absolute), for the key and as the users.
    -> ([Group], {header: reason excluded})"""
    gs = specs(pre, libs, toolbox)
    h = hashlib.sha256()
    for x in (cc, cflags, gs, sorted(NOT_HEADERS.items())):
        h.update(repr(x).encode() + b"\0")
    for p in [os.path.abspath(__file__)] + sorted(staged):
        h.update(p.encode() + b"\0")
        with open(p, "rb") as f:
            h.update(hashlib.sha256(f.read()).digest())
    key = h.hexdigest()
    cache = os.path.join(out, "hdrgroups.json")
    res = None
    try:
        with open(cache) as f:
            c = json.load(f)
        if c.get("key") == key:
            res = [Group.from_json(g) for g in c["groups"]], c["excluded"]
    except (OSError, ValueError, KeyError):
        pass
    if res is None:
        users = sorted(os.path.relpath(p, pre) for p in staged
                       if p.startswith(pre + os.sep) and p.endswith((".c", ".h")))
        res = discover(pre, gs, cc, cflags, users, jobs, os.path.join(out, "tmp", "hdrgroups"))
        with open(cache + ".tmp", "w") as f:
            json.dump({"key": key, "groups": [g.to_json() for g in res[0]], "excluded": res[1]},
                      f, indent=1, sort_keys=True)
        os.replace(cache + ".tmp", cache)
    write_units(out, res[0])
    return res


def load(out):
    """The groups make capps worked out: ([Group], {header: reason})."""
    with open(os.path.join(out, "hdrgroups.json")) as f:
        c = json.load(f)
    return [Group.from_json(g) for g in c["groups"]], c["excluded"]


def unit_path(out, g):
    return os.path.join(out, "hdrunits", g.name + ".c")


def write_units(out, gs):
    d = os.path.join(out, "hdrunits")
    os.makedirs(d, exist_ok=True)
    want = set()
    for g in gs:
        p = unit_path(out, g)
        want.add(os.path.basename(p))
        t = g.unit_text()
        try:
            with open(p) as f:
                if f.read() == t:
                    continue
        except OSError:
            pass
        with open(p, "w") as f:
            f.write(t)
    for f in os.listdir(d):
        if f not in want:
            os.remove(os.path.join(d, f))
