#!/usr/bin/env python3
"""mkcmosdefault.py IN.bin OUT.c -- ROSGD's default CMOS, as a C table.

IN.bin is the team emulator's seed for a HostFS share (RISCOSQEMUA72's
cmos-hostfs.bin): its stock cmos.bin with FileSystem HostFS, made by

    qemu/riscos-pi4/tools/mkcmos.py --symbols .../cmos-symbols-530.json \\
        --base riscos-images/cmos.bin --filesystem 220 -o cmos_default.bin

2048 bytes in logical order, then the OS version word (runtime/cmos.c).
"""
import struct
import sys

data = open(sys.argv[1], "rb").read()
if len(data) != 2052:
    sys.exit(f"mkcmosdefault: {sys.argv[1]} is {len(data)} bytes, not 2052")
version = struct.unpack("<I", data[2048:])[0]
if not 500 <= version < 600:
    sys.exit(f"mkcmosdefault: version {version} is not a RISC OS 5 CMOS")
lines = ["/* generated by tools/mkcmosdefault.py from %s: do not edit. */" % sys.argv[1],
         "#include \"rosgd/cmos.h\"", "",
         "const uint8_t ros_cmos_default[ROS_CMOS_SIZE + 4] = {"]
for i in range(0, len(data), 16):
    lines.append("    " + " ".join("0x%02x," % b for b in data[i:i + 16]))
lines.append("};")
open(sys.argv[2], "w").write("\n".join(lines) + "\n")
