#!/usr/bin/env python3
"""mkresources.py [[--dated] RESOURCES]... OUT.c -- the ROM's files, as one
ResourceFS block.

The roots' trees are merged: resources/, and the files the build makes
(ColourTrans's tables, from RISC OS's maketables; the ROM's applications,
tools/mkromapps.py).  A root after --dated is one whose files carry their
datestamps: its files' modification times (the ROM's applications, dated
as their RISC OS sources are); the others' are 0.  A root's .attributes,
if it has one (tools/mkromapps.py's), gives its files' attributes: a line
per file, its path under the root and the attributes in hex; any other
file's are &11, read and public read.

Each file under RESOURCES becomes an entry in the format that
ResourceFS_RegisterFiles takes (Kernel's ResourceFS, s/ResourceFS):

    +0   offset from here to the next entry (0: the end)
    +4   load address  (&FFFtttdd: filetype ttt -- a ",ttt" suffix on the
         file's name gives it, as RISC OS's build trees do; text, &FFF,
         otherwise -- and dd the datestamp's top byte)
    +8   exec address  (the datestamp's low word: centiseconds since 1900)
    +12  length
    +16  attributes (read, and public read; or as the root's .attributes says)
    +20  name, from $, "." between parts, 0-terminated, word-aligned
    then the length + 4, and the data, word-aligned

The block is a C array, copied into the RMA by the Messages module.

A leaf name that starts with "_" is registered with "/" there instead:
RISC OS names may hold "/" (the fonts' base encodings are "/Base0" and
"/Default"), host names may not; RISC OS's ROMFonts module uses the same
convention for its sources.
"""
import os
import struct
import sys

FILETYPE_TEXT = 0xFFF


def riscos_leaf(leaf):
    """A host leaf name as RISC OS's: its type suffix off, "_" to "/"
    at the start"""
    ftype = FILETYPE_TEXT
    if len(leaf) > 4 and leaf[-4] == ",":
        try:
            ftype = int(leaf[-3:], 16)
            leaf = leaf[:-4]
        except ValueError:
            pass
    if leaf.startswith("_"):
        leaf = "/" + leaf[1:]
    return leaf, ftype


# 1900 to 1970, in seconds: RISC OS's datestamps count from 1900
EPOCH_1900 = 2208988800


ATTR_DEFAULT = 0x11


def attribute_map(root):
    """A root's .attributes: {path under the root: attributes}"""
    got = {}
    path = os.path.join(root, ".attributes")
    if os.path.isfile(path):
        for line in open(path):
            if line.strip():
                name, attr = line.rsplit(None, 1)
                got[name] = int(attr, 16)
    return got


def entries(root, dated):
    attrs = attribute_map(root)
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for f in sorted(filenames):
            if f.startswith(".") or f == "README.md":
                continue
            path = os.path.join(dirpath, f)
            rel = os.path.relpath(path, root).split(os.sep)
            leaf, ftype = riscos_leaf(rel[-1])
            stamp = (int(os.stat(path).st_mtime) + EPOCH_1900) * 100 if dated else 0
            yield (".".join(rel[:-1] + [leaf]), ftype, stamp, open(path, "rb").read(),
                   attrs.get("/".join(rel), ATTR_DEFAULT))


def pad(b):
    return b + b"\0" * (-len(b) % 4)


def block(roots):
    """roots: (directory, dated) pairs"""
    out = b""
    for name, ftype, stamp, data, attr in (e for root in roots for e in entries(*root)):
        head = struct.pack("<IIII", 0xFFF00000 | ftype << 8 | stamp >> 32 & 0xFF,
                           stamp & 0xFFFFFFFF, len(data), attr)
        body = pad(name.encode() + b"\0") + struct.pack("<I", len(data) + 4) + pad(data)
        out += struct.pack("<I", 4 + len(head) + len(body)) + head + body
    return out + struct.pack("<I", 0)


def main():
    args, dest = sys.argv[1:-1], sys.argv[-1]
    roots, dated = [], False
    for a in args:
        if a == "--dated":
            dated = True
        else:
            roots.append((a, dated))
            dated = False
    data = block(roots)
    lines = ["/* generated by tools/mkresources.py: do not edit. */",
             "#include <stdint.h>", "",
             "const uint32_t ros_rom_resources_size = %d;" % len(data),
             "const uint8_t ros_rom_resources[] __attribute__((aligned(4))) = {"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    open(dest, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
