#!/usr/bin/env python3
"""An x32 or A64X32 C module's image as a ROM unit: the bytes, the base
and size, a no-op register_code (its code is not thunk-registered as a
compiled ObjAsm module's is -- rom.c copies it to the RMA and registers
the range when it starts it), and a header naming them.  Written for the
ColourPicker (docs/spec/oslcr 3.4); the ROM images it beside the compiled
modules', at a base of its own.

The machine is the image's (e_machine): x32's for the Intel box, A64X32's
(design 26 P5) for the Apple Silicon box, whose module a loader must put
at a 4 KB boundary in the RMA (its PT_LOAD's p_align: adrp moves only by
whole pages).  Anything else is refused.

LIMIT, if given, is the room the ROM has for it at BASE: a bigger image is
refused, rather than laid over the next one's (SparkFS's modules sit in
slots of their own, one after another).

usage: mkromx32.py NAME BASE IMAGE OUT_C OUT_H [LIMIT]
"""
import sys


def main():
    if len(sys.argv) not in (6, 7):
        sys.exit(__doc__)
    name, base, image, out_c, out_h = sys.argv[1:6]
    with open(image, "rb") as f:
        data = f.read()
    base = int(base, 0)
    if len(sys.argv) == 7 and len(data) > int(sys.argv[6], 0):
        sys.exit("mkromx32: %s: %d bytes, more than the %s the ROM has for it at &%08X"
                 % (image, len(data), sys.argv[6], base))
    machine = int.from_bytes(data[18:20], "little") if data[:5] == b"\x7fELF\x01" else None
    kind = {62: "x32", 183: "A64X32"}.get(machine)
    if kind is None:
        sys.exit("mkromx32: %s: not an x32 or A64X32 module (ELF32 EM_X86_64 or EM_AARCH64)" % image)

    ident = name.lower()
    with open(out_c, "w") as f:
        f.write(f"/* {out_c.split('/')[-1]} -- the {name} module's {kind} image, as the ROM holds it.\n"
                f" * Generated by tools/mkromx32.py from {image}: do not edit. */\n"
                "#include <stdint.h>\n\n"
                f"const uint32_t rom_{ident}_base = 0x{base:08X}u;\n"
                f"const uint32_t rom_{ident}_size = 0x{len(data):X}u;\n"
                f"const uint8_t rom_{ident}[] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + " ".join(f"0x{b:02X}," for b in data[i:i + 16]) + "\n")
        f.write("};\n\n"
                f"/* No dispatcher entries to register: the runtime enters the module's\n"
                f" * own .rosentry veneers (rom.c's {kind} path). */\n"
                f"void {ident}_register(void) {{ }}\n")

    with open(out_h, "w") as f:
        guard = f"ROM_{ident.upper()}_H"
        f.write(f"/* {out_h.split('/')[-1]} -- where the {name} module's image is in the ROM.\n"
                f" * Generated by tools/mkromx32.py: do not edit. */\n"
                f"#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n\n"
                f"extern const uint32_t rom_{ident}_base;\n"
                f"extern const uint32_t rom_{ident}_size;\n"
                f"extern const uint8_t rom_{ident}[];\n"
                f"void {ident}_register(void);\n\n#endif\n")


if __name__ == "__main__":
    main()
