#!/usr/bin/env python3
"""mkttxfont.py VDUTTX OUT.c -- the kernel's teletext font, as C.

VDUTTX is Kernel/s/vdu/vduttx from RISC OS 5's sources (Apache 2.0,
Copyright 1996 Acorn Computers Ltd): TTXHardFont, the HiResTTX half --
characters &20 to &7F, twenty halfwords each (DCW), the top row first, bit 15
the leftmost of sixteen pixels (Kernel/Docs/HiResTTX: a 16 x 20 font drawn
for RISC OS, after Zap's).  The output is committed (runtime/vdu/ttxfont.c),
so a build needs no RISC OS sources; run this again only to take a newer font.
"""
import re
import sys


# The kernel's comments name these with Latin-1 characters, or none: the
# teletext set's own glyphs (the UK set of the SAA5050)
SPECIAL = {0x23: "pound sign", 0x5B: "left arrow", 0x5C: "one half", 0x5D: "right arrow",
           0x5E: "up arrow", 0x5F: "hash", 0x60: "long dash", 0x7B: "one quarter",
           0x7C: "double bar", 0x7D: "three quarters", 0x7E: "divide", 0x7F: "block"}


def main():
    src, dest = sys.argv[1], sys.argv[2]
    rows = []
    state = 0                       # 0 before TTXHardFont, 1 in [ HiResTTX, 2 done
    for line in open(src, encoding="latin-1"):
        if state == 0:
            if line.startswith("TTXHardFont"):
                state = 1
            continue
        if state == 1 and line.strip().startswith("|"):
            break                   # the low-resolution font follows
        m = re.match(r"\s*DCW\s+((?:&[0-9A-Fa-f]{4},){19}&[0-9A-Fa-f]{4})\s*;?(.*)", line)
        if m:
            words = [int(w[1:], 16) for w in m.group(1).split(",")]
            rows.append((words, m.group(2).strip()))
    if len(rows) != 96:
        sys.exit(f"mkttxfont: {len(rows)} characters, want 96")
    hdr = ['/* Copyright 1996 Acorn Computers Ltd', ' *', ' * Licensed under the Apache License, Version 2.0 (the "License");', ' * you may not use this file except in compliance with the License.', ' * You may obtain a copy of the License at', ' *', ' *     http://www.apache.org/licenses/LICENSE-2.0', ' *', ' * Unless required by applicable law or agreed to in writing, software', ' * distributed under the License is distributed on an "AS IS" BASIS,', ' * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.', ' * See the License for the specific language governing permissions and', ' * limitations under the License.', ' *', " * This file is a conversion into C of the font data in RISC OS Open's Kernel", ' * source (Sources/Kernel: s.vdu.vduttx).', ' */']
    out = hdr + ["/* ttxfont.c -- the kernel's teletext font, characters &20 to &7F. It is", " * generated by tools/mkttxfont.py from RISC OS 5's Kernel/s/vdu/vduttx,", " * TTXHardFont's HiResTTX table. Each character is twenty rows, with the top", ' * row first and bit 15 the leftmost of sixteen pixels. The names are the', " * kernel's. They are the characters as teletext shows them, where &23 is a", ' * pound sign and &5F is a hash. */',
           "#include <stdint.h>", "",
           "const uint16_t ros_vdu_ttx_font[96][20] = {"]
    for i, (w, name) in enumerate(rows):
        name = SPECIAL.get(0x20 + i, name)
        out.append("    { " + ", ".join(f"0x{x:04X}" for x in w[:10]) + ",")
        out.append("      " + ", ".join(f"0x{x:04X}" for x in w[10:]) +
                   f" }},  /* &{32 + i:02X} {name[:40]} */")
    out.append("};")
    open(dest, "w").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
