#!/usr/bin/env python3
"""mktypemap.py TYPEMAP OUT.c -- HostFS's extension table, as C.

TYPEMAP is "ext<TAB>type<TAB>name<TAB>description" lines, the table the
team's HostFS reads (RISCOSQEMUA72 riscos-pi4/hostfs/typemap.txt, from
ROOL's filetype allocation list).  No executable type may appear: an
extension is a guess, and a guess must not make a host file code.
"""
import sys

EXECUTABLE = {0xFFA, 0xFF8, 0xFFC, 0xFEB, 0xFFB, 0xFFE}


def main():
    src, dest = sys.argv[1], sys.argv[2]
    rows = []
    for line in open(src, encoding="utf-8"):
        if line.startswith("#") or not line.strip():
            continue
        f = line.rstrip("\n").split("\t")
        if len(f) < 2:
            continue
        t = int(f[1], 16)
        if t in EXECUTABLE:
            sys.exit(f"mktypemap: {f[0]} maps to executable type &{t:03X}")
        rows.append((f[0].lower(), t))
    out = ["/* generated by tools/mktypemap.py: do not edit. */",
           "#include <stdint.h>", "",
           "const struct ros_typemap_entry { const char *ext; uint16_t type; } ros_typemap[] = {"]
    for ext, t in rows:
        out.append('    { "%s", 0x%03X },' % (ext.replace("\\", "\\\\").replace('"', '\\"'), t))
    out.append("};")
    out.append("const unsigned ros_typemap_count = %d;" % len(rows))
    open(dest, "w").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
