#!/usr/bin/env python3
"""Place a compiled module's area in the ROM image.

    romimage.py NAME OBJECT.o MAP BASE OUTDIR

A compiled module's instructions never execute -- the C the compiler made
from them does -- but its area's *bytes* must still be at their assembled
addresses: ObjAsm code areas mix instructions with literal pools, tables,
strings and error blocks, and compiled code reads them by address
(data in code areas stays where the code expects it).  So each module's area goes into the ROM image at BASE, with
its relocations applied, and the runtime maps the image at &FC000000.

Inputs are what rosasm writes: the object as ELF (`--elf`), for the area's
bytes and relocations; and the expansion map (`--map`), for every label's
offset -- ObjAsm keeps local labels out of the object, and compiled code
needs them all.

Writes OUTDIR/rom_NAME.c (the bytes) and OUTDIR/rom_NAME.h (the base and
every label's address, as NAME_Label).
"""

import re
import struct
import sys

R_ARM_ABS32 = 2


def read_elf(path):
    """The one area's bytes and its ABS32 relocations (offset, symbol)."""
    d = open(path, "rb").read()
    if d[:4] != b"\x7fELF" or d[4] != 1 or d[5] != 1:
        raise SystemExit(f"{path}: not an ELF32 little-endian object")
    shoff, = struct.unpack_from("<I", d, 0x20)
    shnum, shstrndx = struct.unpack_from("<HH", d, 0x30)
    secs = [struct.unpack_from("<IIIIIIIIII", d, shoff + i * 40) for i in range(shnum)]
    shstr = secs[shstrndx]
    names = d[shstr[4]:shstr[4] + shstr[5]]

    def name(off):
        return names[off:names.index(b"\0", off)].decode()

    area, relocs = None, []
    for i, s in enumerate(secs):
        n = name(s[0])
        if s[1] == 1 and s[2] & 2:              # PROGBITS, ALLOC
            if area is not None:
                raise SystemExit(f"{path}: more than one area; not handled yet")
            area = (i, bytearray(d[s[4]:s[4] + s[5]]))
        if s[1] == 9:                           # REL
            for k in range(s[5] // 8):
                off, info = struct.unpack_from("<II", d, s[4] + k * 8)
                relocs.append((s[7], off, info >> 8, info & 0xFF))
    if area is None:
        raise SystemExit(f"{path}: no area")
    for target, off, sym, kind in relocs:
        if target != area[0]:
            continue
        if kind != R_ARM_ABS32:
            raise SystemExit(f"{path}: relocation type {kind} at +{off:#x} is "
                             f"not handled yet")
    return area[1], [(off, sym) for target, off, sym, kind in relocs
                     if target == area[0]]


def read_labels(path):
    """Label -> offset, from rosasm's --map: a label is a source line that
    starts in its first column."""
    labels = {}
    rx = re.compile(r"^\s*\d+\s+([0-9A-F]{8})\s+\d+\s+\S+:\d+  (.*)$")
    for line in open(path, encoding="latin-1"):
        m = rx.match(line.rstrip("\n"))
        if m:
            lm = re.match(r"[A-Za-z_]\w*", m.group(2))
            if lm:
                labels.setdefault(lm.group(0), int(m.group(1), 16))
    return labels


def main():
    if len(sys.argv) != 6:
        raise SystemExit(__doc__)
    name, obj, mapfile, base, outdir = sys.argv[1:]
    base = int(base, 0)
    data, relocs = read_elf(obj)
    # Every relocation in a one-area module is against that area: the
    # assembled word is an offset within it, and becomes an address.
    for off, _sym in relocs:
        word, = struct.unpack_from("<I", data, off)
        struct.pack_into("<I", data, off, word + base)
    labels = read_labels(mapfile)

    upper = name.upper()
    with open(f"{outdir}/rom_{name}.c", "w") as fh:
        fh.write(f"/* rom_{name}.c -- {name}'s area, placed at &{base:08X} with its\n"
                 f" * {len(relocs)} relocation(s) applied.  Generated by tools/romimage.py\n"
                 f" * from rosasm's output: do not edit. */\n"
                 f"#include <stdint.h>\n\n"
                 f"const uint32_t rom_{name}_base = 0x{base:08X}u;\n"
                 f"const uint32_t rom_{name}_size = {len(data)}u;\n"
                 f"const uint8_t rom_{name}[{len(data)}] = {{\n")
        for i in range(0, len(data), 12):
            fh.write("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 12]) + ",\n")
        fh.write("};\n")
    with open(f"{outdir}/rom_{name}.h", "w") as fh:
        fh.write(f"/* rom_{name}.h -- where {name}'s labels are in the ROM image.\n"
                 f" * Generated by tools/romimage.py: do not edit. */\n"
                 f"#ifndef ROM_{upper}_H\n#define ROM_{upper}_H\n\n#include <stdint.h>\n\n"
                 f"extern const uint32_t rom_{name}_base;\n"
                 f"extern const uint32_t rom_{name}_size;\n"
                 f"extern const uint8_t rom_{name}[];\n\n")
        for label, off in sorted(labels.items(), key=lambda kv: kv[1]):
            fh.write(f"#define {upper}_{label} 0x{base + off:08X}u\n")
        fh.write(f"\n#endif\n")
    print(f"rom: {name}, {len(data)} bytes at &{base:08X}, "
          f"{len(labels)} labels, {len(relocs)} relocations")


if __name__ == "__main__":
    main()
